package com.openelements.spring.base.data;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Mapped superclass that all JPA entities in the platform should extend.
 *
 * <p>Provides three things every entity needs:
 *
 * <ul>
 *   <li>A {@link UUID} primary key generated by Hibernate at insert time.
 *   <li>A {@code createdAt} timestamp set by Hibernate via {@link CreationTimestamp} on insert and
 *       never modified afterwards.
 *   <li>An {@code updatedAt} timestamp set by Hibernate via {@link UpdateTimestamp} on every
 *       successful update.
 * </ul>
 *
 * <p>{@link #equals(Object)} and {@link #hashCode()} are implemented in terms of the id only, which
 * is the canonical pattern for JPA entities (two entities with the same id refer to the same row,
 * regardless of the values of any other column).
 *
 * <h2>Example</h2>
 *
 * <pre>{@code
 * @Entity
 * @Table(name = "books")
 * public class BookEntity extends AbstractEntity {
 *
 *   @Column(name = "title", nullable = false)
 *   private String title;
 *
 *   public String getTitle() { return title; }
 *   public void setTitle(String title) { this.title = title; }
 * }
 * }</pre>
 */
@MappedSuperclass
public abstract class AbstractEntity implements DbEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.UUID)
  @Column(name = "id", updatable = false, nullable = false)
  private UUID id;

  @CreationTimestamp
  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @UpdateTimestamp
  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  /**
   * {@inheritDoc}
   *
   * @return the entity id, or {@code null} if the entity has not been persisted yet
   */
  public UUID getId() {
    return id;
  }

  /** {@inheritDoc} */
  public void setId(final UUID id) {
    this.id = id;
  }

  /**
   * Returns the moment at which this entity was first persisted.
   *
   * @return the creation timestamp, or {@code null} if the entity has not been persisted yet
   */
  public Instant getCreatedAt() {
    return createdAt;
  }

  /**
   * Returns the moment of the most recent update to this entity.
   *
   * @return the update timestamp, or {@code null} if the entity has not been persisted yet
   */
  public Instant getUpdatedAt() {
    return updatedAt;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    return Objects.equals(id(), ((AbstractEntity) o).id());
  }

  @Override
  public int hashCode() {
    return Objects.hash(id());
  }
}
